version: '3.9'
services:
  python:
    image: raulscontainerreg.azurecr.io/best-city-python:latest
    container_name: python-sentiment-etl
    build:
      context: ./
      dockerfile: ./containers/python/Dockerfile
    working_dir: /opt/app
    tty: true
    env_file:
      - .env_demo
    depends_on:
      - db
  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: best_city
    ports:
      - 5432:5432
    volumes:
      - ./src/queries/best_city_db_init:/docker-entrypoint-initdb.d/
  metabasedb:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: metabaseappdb
    ports:
      - 5431:5432
    volumes:
      - ./src/queries/metabase_db_init:/docker-entrypoint-initdb.d/
  metabase:
    env_file:
      - .env_demo
    image: metabase/metabase:v0.48.3
    container_name: metabase
    hostname: metabasedb
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabaseappdb
      MB_DB_PORT: 5431
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5
    depends_on:
      - metabasedb
      - python
